image: gettingstarted.gif
title: Getting Started
author: Casey Reas and Ben Fry
introduction: Welcome to Processing! This tutorial covers the basics of writing Processing code in R mode.
level: Beginner
